import { Link } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ScrollText, Info } from "lucide-react";

const LAST_UPDATED = "May 21, 2026";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1">
        <section className="gradient-hero">
          <div className="container mx-auto px-4 py-12 md:py-16 text-center">
            <div className="mx-auto mb-4 inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-lemon/40 animate-bounce-gentle">
              <ScrollText className="w-8 h-8 text-foreground" />
            </div>
            <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground">
              Terms of <span className="text-gradient">Service</span>
            </h1>
            <p className="text-muted-foreground mt-3 text-sm">Last updated: {LAST_UPDATED}</p>
          </div>
        </section>

        <section className="container mx-auto px-4 py-10 max-w-3xl">
          <div className="rounded-2xl border border-border bg-muted/30 p-4 mb-8 flex items-start gap-3 text-sm">
            <Info className="w-5 h-5 mt-0.5 flex-shrink-0 text-foreground" />
            <p className="text-muted-foreground">
              This is a starter template written in plain English. It is not legal advice. We
              will revise it as the product evolves. Questions can go through our{" "}
              <Link to="/contact" className="text-primary font-bold hover:underline">Contact page</Link>.
            </p>
          </div>

          <article className="space-y-8 text-foreground/90 leading-relaxed">
            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Acceptance</h2>
              <p>
                By creating an account or using Marathi Mitra (the "Service"), you agree to
                these Terms and our{" "}
                <Link to="/privacy" className="text-primary font-bold hover:underline">Privacy Policy</Link>.
                If you do not agree, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Who can use the Service</h2>
              <ul className="list-disc pl-6 space-y-1.5 text-muted-foreground">
                <li>Accounts may only be created by adults (18+) who are a parent or legal guardian.</li>
                <li>Children may use the Service only under the supervision of the adult account holder.</li>
                <li>You confirm you have authority to create profiles for the children on your account.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">What the Service does</h2>
              <p className="text-muted-foreground">
                Marathi Mitra is an educational app that helps children practice spoken
                Marathi through AI-powered conversations, structured lessons, and game-based
                missions. The Service is not a substitute for a qualified teacher or for
                family time spent learning the language together.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">AI-generated content</h2>
              <p className="text-muted-foreground">
                Lesson responses, chat replies, mission narratives, and digest emails are
                generated by AI language models. They can be inaccurate or occasionally
                incorrect. We do our best to keep them age-appropriate and useful, but you
                should treat AI output as a study aid, not a definitive answer. Educational
                content should be verified by qualified educators or parents.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Your account</h2>
              <ul className="list-disc pl-6 space-y-1.5 text-muted-foreground">
                <li>Keep your password private. You are responsible for activity on your account.</li>
                <li>Provide accurate information (a working email, a real name for the parent).</li>
                <li>Tell us promptly if you suspect someone else has accessed your account.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Acceptable use</h2>
              <p className="mb-2 text-muted-foreground">Please do not:</p>
              <ul className="list-disc pl-6 space-y-1.5 text-muted-foreground">
                <li>Try to break, scrape, or overload the Service.</li>
                <li>Use the Service to harass, harm, or impersonate others.</li>
                <li>Attempt to extract or copy the lesson content for resale.</li>
                <li>Bypass safety, rate-limiting, or guardrail features.</li>
                <li>Use the Service in ways that violate applicable law.</li>
              </ul>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Ownership</h2>
              <p className="text-muted-foreground">
                The Marathi Mitra app, lesson content, mission templates, the Mitra
                character, design, and brand are owned by us. You may use them for personal,
                non-commercial educational purposes through the Service. The chat messages
                your child sends remain yours; we process them to provide the Service, as
                described in the{" "}
                <Link to="/privacy" className="text-primary font-bold hover:underline">Privacy Policy</Link>.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Ending the relationship</h2>
              <p className="text-muted-foreground">
                You can delete your account at any time by writing to us through the{" "}
                <Link to="/contact" className="text-primary font-bold hover:underline">Contact page</Link>.
                We may suspend or close accounts that violate these Terms, abuse the Service,
                or put other users at risk.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Disclaimers</h2>
              <p className="text-muted-foreground">
                The Service is provided "as is" and "as available." We do not warrant that it
                will be uninterrupted, error-free, or fit for any particular purpose. We are
                not responsible for educational outcomes, inaccuracies in AI output, or
                damages arising from your use of the Service, to the maximum extent allowed
                by law.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Changes to these Terms</h2>
              <p className="text-muted-foreground">
                We may update these Terms from time to time. When we make a material change
                we will update the "Last updated" date above and, where appropriate, email
                account holders. Continued use after a change means you accept the new Terms.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl font-bold mb-2">Contact</h2>
              <p className="text-muted-foreground">
                For any question about these Terms, reach us through the{" "}
                <Link to="/contact" className="text-primary font-bold hover:underline">Contact page</Link>.
              </p>
            </section>
          </article>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
